### PR TITLE
Allow dictionaries to define client_secrets

### LINKED ISSUE #64: Allow client_secrets as a dictionary
Currently the load_secrets function will always look for a file to open and read. Is there a reason for not allowing this function to load the secrets from a dictionary passed in instead of loading from a file?

I do not want to save a static file on my root directory with all the secrets. I would like to be able to obtain the secrets programatically and not have to store any secrets on the file system.

### PR DESCRIPTION
**Pull request by stanleykylee**
This PR is to fix #64, please let me know if this is works for you @puiterwijk ?

### CODE REVIEW

**Comment by puiterwijk** [comment]
Sure, this works for me. Thanks!

**Comment by nnkteja** [comment]
@puiterwijk @stanleykylee I'm unable to find it in the package from pypi https://pypi.org/project/flask-oidc/. Can you please check and fix it.

**Comment by stanleykylee** [comment]
@nnkteja , you won't see it in pypi because the version that is in pypi is 1.4.0 from commit 9cc725d in April 2018. The merge with my PR was in Nov 2018 was is after the 1.4.0 release. @puiterwijk will need to cut a new release to include the later commits for it to be in pypi. You can still just install this yourself locally by grabbing the latest code from this repo and using it as a local module.

**Comment by nnkteja** [comment]
Thanks @stanleykylee, I want to use this on production server, so I will need a pip package. @puiterwjik can you please release a version this change.

**Pull request merged**
