### PR TITLE
Added decorator to check a client role from Keycloak

### PR DESCRIPTION
**Pull request by kevin-thorpe**
I needed a way to validate pages in my Flask application against specific roles from Keycloak in the access token and the @accept_token approach wasn't working for html pages. I've added a new decorator function to allow this and return the page or 403 FORBIDDEN. Use as follows:
```
@app.route("/private")
@oidc.require_login
@iodc.require_role('keycloak_client', 'keycloak_role')
def private():
    return "Hello"
```

### CODE REVIEW

**Comment by gary-cowell** [comment]
I found I had to make the following additional changes.

Firstly to add base64 padding to the token to allow it to decode.

Secondly, to prevent failure if user has no roles assigned.

```
@@ -503,8 +503,12 @@
             @wraps(view_func)
             def decorated(*args, **kwargs):
                 pre, tkn, post = self.get_access_token().split('.')
-                access_token = json.loads(b64decode(tkn))
-                if role in access_token['resource_access'][client]['roles']:
+                access_token = json.loads(urlsafe_b64decode(tkn + '===' ))
+                try:
+                    roles=access_token['resource_access'][client]['roles']
+                except KeyError:
+                    roles=[]
+                if role in roles:
                     return view_func(*args, **kwargs)
                 else:
                     return abort(403)

```

**Comment by styk-tv** [comment]
@puiterwijk can we please merge this?. Official confirmation from you for Keycloak support would be fantastic.

**Comment by franciscoed** [comment]
Hi guys, this one looks nice. I need that too.
Any plans to merge?

**Comment by puiterwijk** [comment]
Hi, thanks for your patch!
I will manually merge this, since I can't take the `setup.py` changes (I'll bump the verison in a future patch after testing everything).
While I think the current way this is being done is not ideal, I will take this patch and add it to the documentation, but renaming it to `require_keycloak_role.
Afterwards, when I get a better idea for an implementation, I'll make sure it's backwards compatible.

**Pull request closed without merging**
